### ISSUE TITLE
ORM log bug + IsValid

### ISSUE THREAD

**Issue by IstuntmanI** [pBlueG/SA-MP-MySQL#69]
>Log("18:31:12","orm_destroy",4,"orm_id: 0",0);
>Log("18:31:12",""orm_destroy"",1,"invalid orm id (id: 0)",0);

As you can see, when logging the error of an invalid orm id, "orm_destroy" is surrounded by 2 pairs of ", so the HTML page is no longer being printed due to this.

Also, we need orm_isvalid, to check before destroying if the specified orm id is valid.

**Comment by maddinat0r** [comment]
Are you sure you're using the latest version? This bug was fixed more than a year ago in e4d9532406824d71814b905406c8699aebb26a7a.

And why do you need to check if the ORM ID is valid before destroying it? `orm_destroy` already does this (returns 0 if ID is invalid, just like every other ORM function).

**Comment by IstuntmanI** [comment]
>[29/09/2015 04:55:46]  Loading plugin: mysql.so
>[29/09/2015 04:55:46]  >> plugin.mysql: R39-2 successfully loaded.
Oops. I could bet that I am using the last one. But now I have problems:
>Failed (/usr/lib32/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by plugins/mysql.so))
I am receiving this error on both CentOS and Debian versions of the plugin. The "linux" static one from R39-2 was working alright. :c

I need to do that because the "invalid orm id" error appears in mysql_log. I tried to do that with variable checking and setting when destroyed, but I see that it still appears (this is something bad from my side, but still, orm_isvalid is still needed for this case).

**Comment by maddinat0r** [comment]
Which OS is your shared hosted running on? I need a name, a version number and the architecture (i686/amd64).

**Comment by IstuntmanI** [comment]
This is their response: "amd64 but you need a i386 (32 bits) library for SA:MP" . "Ubuntu EGLIBC 2.11.1-0ubuntu7.12" - so I guess it's Ubuntu 7.12.

I hope this response is helpful.

**Comment by Mellnik** [comment]
It's Ubuntu 10.04, which is outdated.

**Comment by IstuntmanI** [comment]
Well, a download link should still be provided for MySQL for it. Shared hosts are most of the time outdated because server owners aren't using new methods. (AFAIK, this one is using MySQL 5.0, which is pretty old too)

**Comment by maddinat0r** [comment]
I'll think about recompiling it. 
R39-2 works, because I used an older compiler. Then I started development on R40 and upgraded my compiler.
And by the way, you won't be able to upgrade to R40 with that old OS version, because it relies on newer C++ language features, which requires a newer compiler version (GCC >= 4.8.x).

**Comment by IstuntmanI** [comment]
Damn Damn Damn Damn Damn Damn Damn Damn Damn Damn Damn Damn Damn ! Damn !

I guess that there's no way for R40 to be made compatible with that OS. D:

**Comment by maddinat0r** [comment]
Not without rewriting the whole code - again.

**Comment by IstuntmanI** [comment]
Fml. :c At least try to compile R39-3 for it ? D:

**Comment by maddinat0r** [comment]
Recompiled R39-3 on CentOS 6 and Debian 6 (default "linux" package).
